Create notebook introducing workspace resources
DataBiosphere/terra-axon-examples pull request #31
Opened 2023-05-19 15:06 UTC by emmarogge

Create notebook introducing the types of referenced and controlled resources which can be added to Verily Workbench resources. Provide widgets for adding each type of referenced and controlled resource to the user's current workspace.

2023-05-23 00:04 UTC, wnojopra requested changes

2023-05-23 00:04 UTC, wnojopra commented on first_hour_on_terra/workspace_resource_examples.ipynb
> +    "Both public and private GitHub repositories can be added to data collections. In order to add a private GitHub repository, you must first [set up your Terra SSH key](https://terra-docs.api.veril
```suggestion
    "Both public and private GitHub repositories can be added to data collections. In order to add a private GitHub repository, you must first [set up your Terra SSH key](https://terra-docs.api.verily.com/docs/how_to_guides/terra_ssh_key_guide) and should provide a repo URL of the format `git@github.com` and not `http://`. No additional setup is required to add a public GitHub repository.\n",
```

2023-05-23 00:04 UTC, wnojopra commented on first_hour_on_terra/workspace_resource_examples.ipynb
> +    "        self.label = widgets.Label(value = 'Please provide appropriate values in the input boxes.')\n",
Just like with the data collections notebook, I think it needs to be more clear what the user is expected to input here. Please add instructions here that tells the user that they're expected to make up a repo name and description and give examples of good names. Also give an example of a github url (maybe a public one). I think the cloning options also need some explanations.

2023-05-23 00:04 UTC, wnojopra commented on first_hour_on_terra/workspace_resource_examples.ipynb
> +    "#### 3. Create a GCP notebook\n",
Even though the command is called `create gcp-notebook`, I really think we should call it a cloud environment. https://terra-docs.api.verily.com/docs/how_to_guides/cloud_environments/#accessing-the-terra-command-line-tool-from-your-cloud-environment for example correctly calls it a cloud environment even though the command line example calls it a gcp-notebook.

In fact, I'm going to file a ticket to rename it in the CLI.

2023-05-23 15:11 UTC, emmarogge commented on first_hour_on_terra/workspace_resource_examples.ipynb
> +    "Both public and private GitHub repositories can be added to data collections. In order to add a private GitHub repository, you must first [set up your Terra SSH key](https://terra-docs.api.veril
done!

2023-05-24 19:44 UTC, emmarogge commented on first_hour_on_terra/workspace_resource_examples.ipynb
> +    "#### 3. Create a GCP notebook\n",
awesome! I will update this accordingly once the CLI change lands.

2023-05-24 19:45 UTC, emmarogge commented on first_hour_on_terra/workspace_resource_examples.ipynb
> +    "        self.label = widgets.Label(value = 'Please provide appropriate values in the input boxes.')\n",
I have now gone in and provided detailed explanations for each of the input parameters for each widget. It makes for a longer notebook, overall, but hopefully one that's more useful/less frustrating for users.

2023-05-24 21:04 UTC, emmarogge commented
Closing this PR, continuing in #33

2023-05-31 00:59 UTC, closed without merging