Initial checkin of single cell notebook (HCA).
DataBiosphere/terra-axon-examples pull request #55
Opened 2023-09-12 22:08 UTC by mbookman

2023-09-12 22:24 UTC, wnojopra requested changes
Cool! TIL about `tqdm` and am pleasantly surprised to see its already pre-installed in our cloud env.

2023-09-12 22:24 UTC, wnojopra commented on single_cell/getting-started-with-hca.ipynb
> +    "Run the cell below to set up libraris and utilities for this notebook."
```suggestion
    "Run the cell below to set up libraries and utilities for this notebook."
```

2023-09-12 22:24 UTC, wnojopra commented on single_cell/getting-started-with-hca.ipynb
> +    "HCA_EXAMPLES_DIR=os.path.expanduser('~/terra-tutorials/hca')\n",
nit 
```suggestion
    "HCA_EXAMPLES_DIR = os.path.expanduser('~/terra-tutorials/hca')\n",
```

2023-09-12 22:24 UTC, wnojopra commented on single_cell/getting-started-with-hca.ipynb
> +    "def download_file(url, output_path):\n",
```suggestion
    "def download_file(url: str, output_path: str) -> None:\n",
```

2023-09-12 22:24 UTC, wnojopra commented on single_cell/getting-started-with-hca.ipynb
> +    "    return response"
IMO this should be `return response.json()` since the type hint says this function returns a list

2023-09-12 22:24 UTC, wnojopra commented on single_cell/getting-started-with-hca.ipynb
> +    "            params = None\n",
Are you planning on a follow-up change that calls the next_url? Leave a todo comment if so. Or fix, or remove.

2023-09-13 15:58 UTC, emmarogge reviewed
Please add a README file to the `single_cell` directory in keeping with other directories in this repo. Otherwise, very cool -- LGTM!

2023-09-20 18:27 UTC, mbookman commented on single_cell/getting-started-with-hca.ipynb
> +    "            params = None\n",
Thanks @wnojopra! Total oversight. Handled now.

2023-09-20 19:01 UTC, wnojopra approved these changes
LGTM. Merging main into your branch _should_ fix the dataproc file. Something like:
```
git checkout main
git pull
git checkout mb/single_cell_add_hca
git merge main
```

2023-09-20 21:15 UTC, merged